routes/web.php
<?php


use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function(){

    //cart
    Route::resource('cart', 'App\Http\Controllers\CartController');
    Route::patch('kosongkan/{id}', 'App\Http\Controllers\CartController@kosongkan');
    // cart detail
    Route::resource('cartdetail', 'App\Http\Controllers\CartDetailController');
    // route transaksi
    Route::resource('transaksi', 'App\Http\Controllers\TransaksiController');
    // alamat pengiriman
    Route::resource('alamatpengiriman', 'App\Http\Controllers\AlamatPengirimanController');
    // checkout
    Route::get('checkout', 'App\Http\Controllers\CartController@checkout');
    // rajaongkir
    Route::get('ongkir', 'App\Http\Controllers\OngkirController@ongkir')->name('ongkir');
    Route::get('getcity/ajax/{id}', 'App\Http\Controllers\OngkirController@getCity')->name('getcity.ajax');
    Route::post('getongkir/ajax/{id}', 'App\Http\Controllers\OngkirController@getOngkir')->name('getongkir.ajax');

    Route::get('/', [App\Http\Controllers\Admin\ProdukController::class, 'index'])->name('/');
    Route::resource('produk', App\Http\Controllers\Admin\ProdukController::class);
    Route::resource('kategori', App\Http\Controllers\Admin\KategoriController::class);
    Route::get('isikategori', [App\Http\Controllers\Admin\KategoriController::class, 'isi']);
    Route::resource('rasa', App\Http\Controllers\Admin\RasaController::class);
    Route::get('isirasa', [App\Http\Controllers\Admin\RasaController::class, 'isi']);
    Route::resource('carabayar', App\Http\Controllers\Admin\BayarController::class);
    Route::resource('pengiriman', App\Http\Controllers\Admin\PengirimanController::class);
    Route::resource('cart-session', App\Http\Controllers\CartSessionController::class);

});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/carabayar/form.blade.php
@extends('admin.layouts.app')
@section('title')
     Form {{@$carabayar ? ' Ubah' : ' Tambah'}}
@endsection
@section('carabayar','active')
@section('content')
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Data Cara Bayar</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{url('carabayar')}}">Cara Bayar</a>
                                    </li>
                                    <li class="breadcrumb-item active">{{(@$carabayar ? ' Ubah' : ' Tambah')}} Cara Bayar
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Tables start -->
                <section id="basic-vertical-layouts">
                    <div class="row">
                        <div class=" col-12">
                            <div class="card">
                                <div class="card-body">
                                    @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <h4 class="alert-heading">Error!</h4>
                                            <div class="alert-body">
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        </div>
                                    @endif
                                    <form class="form form-vertical"  action="{{@$carabayar ? route('carabayar.update',$carabayar->id) : route('carabayar.store')}}"
                                          method="POST" enctype="multipart/form-data">
                                        @csrf
                                        @if(@$carabayar)
                                            {{method_field('patch')}}
                                        @endif
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="cara_bayar">Cara Bayar</label>
                                                    <input type="text" id="cara_bayar" class="form-control" name="cara_bayar" placeholder="Cara Bayar"
                                                    value="{{old('cara_bayar', @$carabayar ? $carabayar->cara_bayar : '')}}"/>
                                                </div>
                                            </div>

                                            <div class="col-12">
                                                <button type="submit" class="btn btn-primary mr-1">Submit</button>
                                                <a href="{{url('carabayar')}}" type="reset" class="btn btn-outline-secondary">Cancel</a>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Tables end -->
            </div>
        </div>
    </div>
    @endsection

@push('styles')
@endpush

@push('scripts')
    <script>

    </script>
@endpush

resources/views/admin/carabayar/index.blade.php
@extends('admin.layouts.app')
@section('title','Cara Bayar')
@section('carabayar','active')

@section('content')
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Data Cara Bayar</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
{{--                                    <li class="breadcrumb-item"><a href="{{route('carabayar.index')}}">Cara Bayar</a>--}}
{{--                                    </li>--}}
                                    <li class="breadcrumb-item active">Cara Bayar
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Tables start -->
                <div class="row" id="basic-table">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <a href="{{route('carabayar.create')}}" class="btn btn-primary waves-effect waves-float waves-light">Tambah Cara Bayar</a>
                            </div>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Nama Cara Bayar</th>
                                        <th>Aksi</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($carabayar as $row)
                                        <tr>
                                            <td>{{$loop->iteration}}</td>
                                            <td>{{$row->cara_bayar}}</td>
                                            <td>
                                                <a href="{{route('carabayar.edit', $row->id)}}" class="btn btn-warning waves-effect waves-float waves-light">Edit</a>
                                                <a href="#" data-id="{{$row->id}}" class="btn btn-danger btn-del waves-effect waves-float waves-light">Delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Basic Tables end -->
            </div>
        </div>
    </div>
    @endsection

    @push('styles')
    @endpush
    
    @push('scripts')
        <script>
            $(document).ready(function () {
                $(document).on('click', '.btn-del', function () {
                    var id = $(this).data('id');
                    Swal.fire({
                        icon: 'error',
                        title: 'Are you sure?',
                        text: "You won't be able to revert this!",
                        type: 'error',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Yes, delete it!'
                    })
                        .then((result) => {
                            if (result.value) {
                                $.ajax({
                                    'url': '{{url('carabayar')}}/' + id,
                                    'type': 'post',
                                    'data': {
                                        '_method': 'DELETE',
                                        '_token': '{{csrf_token()}}'
                                    },
                                    success: function (response) {
                                        if (response == 1) {
                                            toastr.error('Data gagal dihapus!', 'Gagal!', {
                                                closeButton: true,
                                                tapToDismiss: false
                                            });
                                        } else {
                                            toastr.success('Data berhasil dihapus!', 'Berhasil!', {
                                                closeButton: true,
                                                tapToDismiss: false
                                            });
                                            location.reload();
                                        }
                                    }
                                });
                            } else {
                                console.log(`dialog was dismissed by ${result.dismiss}`)
                            }
    
                        });
                });
    
            });
    
        </script>
    @endpush