routes/web.php
<?php


use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function(){

    //cart
    Route::resource('cart', 'App\Http\Controllers\CartController');
    Route::patch('kosongkan/{id}', 'App\Http\Controllers\CartController@kosongkan');
    // cart detail
    Route::resource('cartdetail', 'App\Http\Controllers\CartDetailController');
    // route transaksi
    Route::resource('transaksi', 'App\Http\Controllers\TransaksiController');
    // alamat pengiriman
    Route::resource('alamatpengiriman', 'App\Http\Controllers\AlamatPengirimanController');
    // checkout
    Route::get('checkout', 'App\Http\Controllers\CartController@checkout');
    // rajaongkir
    Route::get('ongkir', 'App\Http\Controllers\OngkirController@ongkir')->name('ongkir');
    Route::get('getcity/ajax/{id}', 'App\Http\Controllers\OngkirController@getCity')->name('getcity.ajax');
    Route::post('getongkir/ajax/{id}', 'App\Http\Controllers\OngkirController@getOngkir')->name('getongkir.ajax');

    Route::get('/', [App\Http\Controllers\Admin\ProdukController::class, 'index'])->name('/');
    Route::resource('produk', App\Http\Controllers\Admin\ProdukController::class);
    Route::resource('kategori', App\Http\Controllers\Admin\KategoriController::class);
    Route::get('isikategori', [App\Http\Controllers\Admin\KategoriController::class, 'isi']);
    Route::resource('rasa', App\Http\Controllers\Admin\RasaController::class);
    Route::get('isirasa', [App\Http\Controllers\Admin\RasaController::class, 'isi']);
    Route::resource('carabayar', App\Http\Controllers\Admin\BayarController::class);
    Route::resource('pengiriman', App\Http\Controllers\Admin\PengirimanController::class);
    Route::resource('cart-session', App\Http\Controllers\CartSessionController::class);

});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Pengiriman.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pengiriman extends Model
{
    public $table = 't_pengiriman';
    protected $fillable = ['pengiriman'];

}

app/Http/Controllers/Admin/PengirimanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Pengiriman;
use Illuminate\Support\Facades\DB;
use Auth;

class PengirimanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['pengiriman'] = Pengiriman::orderBy('pengiriman','asc')->get();
        if(Auth::user()->role == 'admin'){
            return view('admin.pengiriman.index', $data);
        }
        elseif(Auth::user()->role == 'user'){
            return view('user.pengiriman.index', $data);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['pengiriman'] = Pengiriman::orderBy('pengiriman','asc')->get();
        if(Auth::user()->role == 'admin'){
            return view('admin.pengiriman.form');
        }
        elseif(Auth::user()->role == 'user'){
            return redirect('/pengiriman');
        }
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rule = [
            'pengiriman' => 'required'
        ];
        $this->validate($request, $rule);

        $input = $request->all();

        $status = Pengiriman::create($input);
        if ($status){
            return redirect('/pengiriman')->with('success','Data berhasil ditambahkan');
        }else{
            return redirect('/pengiriman/create')->with('error','Data gagal ditambahkan');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['pengiriman'] = DB::table('t_pengiriman')->find($id);
        if(Auth::user()->role == 'admin'){
            return view('admin.pengiriman.form', $data);
        }
        elseif(Auth::user()->role == 'user'){
            return redirect('/pengiriman');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['pengiriman'] = DB::table('t_pengiriman')->find($id);
        if(Auth::user()->role == 'admin'){
            return view('admin.pengiriman.form', $data);
        }
        elseif(Auth::user()->role == 'user'){
            return redirect('/pengiriman');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rule = [
            'pengiriman' => 'required'
        ];
        $this->validate($request, $rule);
    
        $input = $request->all();
        // unset($input['_token']);
        // unset($input['_method']);
        // $status = DB::table('t_produk')->where('id', $id)->update($input);

        $pengiriman = Pengiriman::find($id);
        $status = $pengiriman->update($input);
        
        // $tproduk = DB::find($id);
        // if ($request->foto){
        //     $fotoName = time() . '.' . $request->foto->extension();
        //     $request->foto->move(public_path() . '/image/foto/', $fotoName);
        // } else {
        //     $fotoName = $tproduk->foto;
        // }

        if ($status){
            return redirect('/pengiriman')->with('success','Data berhasil diubah');
        }else{
            return redirect('/pengiriman/create')->with('error','Data gagal diubah');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pengiriman = Pengiriman::find($id);
        $status = $pengiriman->delete();
        if ($status){
            return redirect('/pengiriman')->with('success','Data berhasil dihapus');
        }else{
            return redirect('/pengiriman/create')->with('error','Data gagal dihapus');
        }
    }
}

resources/views/admin/pengiriman/form.blade.php
@extends('admin.layouts.app')
@section('title')
     Form {{@$pengiriman ? ' Ubah' : ' Tambah'}}
@endsection
@section('pengiriman','active')
@section('content')
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Data Pengiriman</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{url('pengiriman')}}">Pengiriman</a>
                                    </li>
                                    <li class="breadcrumb-item active">{{(@$pengiriman ? ' Ubah' : ' Tambah')}} Pengiriman
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Tables start -->
                <section id="basic-vertical-layouts">
                    <div class="row">
                        <div class=" col-12">
                            <div class="card">
                                <div class="card-body">
                                    @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <h4 class="alert-heading">Error!</h4>
                                            <div class="alert-body">
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        </div>
                                    @endif
                                    <form class="form form-vertical"  action="{{@$pengiriman ? route('pengiriman.update',$pengiriman->id) : route('pengiriman.store')}}"
                                          method="POST" enctype="multipart/form-data">
                                        @csrf
                                        @if(@$pengiriman)
                                            {{method_field('patch')}}
                                        @endif
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="pengiriman">Pengiriman</label>
                                                    <input type="text" id="pengiriman" class="form-control" name="pengiriman" placeholder="Pengiriman"
                                                    value="{{old('pengiriman', @$pengiriman ? $pengiriman->pengiriman : '')}}"/>
                                                </div>
                                            </div>

                                            <div class="col-12">
                                                <button type="submit" class="btn btn-primary mr-1">Submit</button>
                                                <a href="{{url('pengiriman')}}" type="reset" class="btn btn-outline-secondary">Cancel</a>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Tables end -->
            </div>
        </div>
    </div>
    @endsection

@push('styles')
@endpush

@push('scripts')
    <script>

    </script>
@endpush

resources/views/admin/pengiriman/index.blade.php
@extends('admin.layouts.app')
@section('title','Pengiriman')
@section('pengiriman','active')

@section('content')
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Data Pengiriman</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
{{--                                    <li class="breadcrumb-item"><a href="{{route('pengiriman.index')}}">Pengiriman</a>--}}
{{--                                    </li>--}}
                                    <li class="breadcrumb-item active">Pengiriman
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Tables start -->
                <div class="row" id="basic-table">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <a href="{{route('pengiriman.create')}}" class="btn btn-primary waves-effect waves-float waves-light">Tambah Pengiriman</a>
                            </div>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Nama Pengiriman</th>
                                        <th>Aksi</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($pengiriman as $row)
                                        <tr>
                                            <td>{{$loop->iteration}}</td>
                                            <td>{{$row->pengiriman}}</td>
                                            <td>
                                                <a href="{{route('pengiriman.edit', $row->id)}}" class="btn btn-warning waves-effect waves-float waves-light">Edit</a>
                                                <a href="#" data-id="{{$row->id}}" class="btn btn-danger btn-del waves-effect waves-float waves-light">Delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Basic Tables end -->
            </div>
        </div>
    </div>
    @endsection

    @push('styles')
    @endpush
    
    @push('scripts')
        <script>
            $(document).ready(function () {
                $(document).on('click', '.btn-del', function () {
                    var id = $(this).data('id');
                    Swal.fire({
                        icon: 'error',
                        title: 'Are you sure?',
                        text: "You won't be able to revert this!",
                        type: 'error',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Yes, delete it!'
                    })
                        .then((result) => {
                            if (result.value) {
                                $.ajax({
                                    'url': '{{url('pengiriman')}}/' + id,
                                    'type': 'post',
                                    'data': {
                                        '_method': 'DELETE',
                                        '_token': '{{csrf_token()}}'
                                    },
                                    success: function (response) {
                                        if (response == 1) {
                                            toastr.error('Data gagal dihapus!', 'Gagal!', {
                                                closeButton: true,
                                                tapToDismiss: false
                                            });
                                        } else {
                                            toastr.success('Data berhasil dihapus!', 'Berhasil!', {
                                                closeButton: true,
                                                tapToDismiss: false
                                            });
                                            location.reload();
                                        }
                                    }
                                });
                            } else {
                                console.log(`dialog was dismissed by ${result.dismiss}`)
                            }
    
                        });
                });
    
            });
    
        </script>
    @endpush