routes/web.php
<?php


use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function(){

    //cart
    Route::resource('cart', 'App\Http\Controllers\CartController');
    Route::patch('kosongkan/{id}', 'App\Http\Controllers\CartController@kosongkan');
    // cart detail
    Route::resource('cartdetail', 'App\Http\Controllers\CartDetailController');
    // route transaksi
    Route::resource('transaksi', 'App\Http\Controllers\TransaksiController');
    // alamat pengiriman
    Route::resource('alamatpengiriman', 'App\Http\Controllers\AlamatPengirimanController');
    // checkout
    Route::get('checkout', 'App\Http\Controllers\CartController@checkout');
    // rajaongkir
    Route::get('ongkir', 'App\Http\Controllers\OngkirController@ongkir')->name('ongkir');
    Route::get('getcity/ajax/{id}', 'App\Http\Controllers\OngkirController@getCity')->name('getcity.ajax');
    Route::post('getongkir/ajax/{id}', 'App\Http\Controllers\OngkirController@getOngkir')->name('getongkir.ajax');

    Route::get('/', [App\Http\Controllers\Admin\ProdukController::class, 'index'])->name('/');
    Route::resource('produk', App\Http\Controllers\Admin\ProdukController::class);
    Route::resource('kategori', App\Http\Controllers\Admin\KategoriController::class);
    Route::get('isikategori', [App\Http\Controllers\Admin\KategoriController::class, 'isi']);
    Route::resource('rasa', App\Http\Controllers\Admin\RasaController::class);
    Route::get('isirasa', [App\Http\Controllers\Admin\RasaController::class, 'isi']);
    Route::resource('carabayar', App\Http\Controllers\Admin\BayarController::class);
    Route::resource('pengiriman', App\Http\Controllers\Admin\PengirimanController::class);
    Route::resource('cart-session', App\Http\Controllers\CartSessionController::class);

});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    protected $table = 'cart';
    protected $fillable = [
        'user_id',
        'no_invoice',
        'status_cart',
        'status_pembayaran',
        'status_pengiriman',
        'no_resi',
        'ekspedisi',
        'subtotal',
        'ongkir',
        'diskon',
        'total',
    ];

    public function user() {
        return $this->belongsTo('App\Models\User','user_id');
    }

    public function detail() {
        return $this->hasMany('App\Models\CartDetail', 'cart_id');
    }

    public function updatetotal($itemcart, $subtotal) {
        $this->attributes['subtotal'] = $itemcart->subtotal + $subtotal;
        $this->attributes['total'] = $itemcart->total + $subtotal;
        self::save();
    }
}

app/Models/Cart.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    protected $table = 'cart';
    protected $fillable = [
        'user_id',
        'no_invoice',
        'status_cart',
        'status_pembayaran',
        'status_pengiriman',
        'no_resi',
        'ekspedisi',
        'subtotal',
        'ongkir',
        'diskon',
        'total',
    ];

    public function user() {
        return $this->belongsTo(User::class,'user_id');
    }

    public function detail() {
        return $this->hasMany(CartDetail::class, 'cart_id');
    }

    public function updatetotal($itemcart, $subtotal) {
        $this->attributes['subtotal'] = $itemcart->subtotal + $subtotal;
        $this->attributes['total'] = $itemcart->total + $subtotal;
        self::save();
    }
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cart;
use App\Models\CartDetail;
use App\Models\AlamatPengiriman;
use App\Models\Order;
use Illuminate\Http\Request;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $itemuser = $request->user();//ambil data user
        $itemcart = Cart::where('user_id', @$itemuser->id)
                        ->where('status_cart', 'cart')
                        ->first();
        $cartdetail = CartDetail::where('cart_id', @$itemcart->id)
                                ->get();
        $total = $cartdetail->sum('subtotal');
        $data = array('title' => 'Shopping Cart',
                    'itemcart' => $itemcart,
                    'total' => $total,
                    'cartdetail' => $cartdetail);
        return view('cart.index', $data)->with('no', 1);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function kosongkan($id) {
        $itemcart = Cart::findOrFail($id);
        $itemcart->detail()->delete();//hapus semua item di cart detail
        $itemcart->updatetotal($itemcart, '-'.$itemcart->subtotal);
        return back()->with('success', 'Cart berhasil dikosongkan');
    }

    public function checkout(Request $request) {
        $itemuser = $request->user();
        $itemcart = Cart::where('user_id', $itemuser->id)
                        ->where('status_cart', 'cart')
                        ->first();
        $itemalamatpengiriman = AlamatPengiriman::where('user_id', $itemuser->id)
                                                ->where('status', 'utama')
                                                ->first();
        if ($itemcart) {
            $data = array('title' => 'Checkout',
                        'itemcart' => $itemcart,
                        'itemalamatpengiriman' => $itemalamatpengiriman);
            return view('cart.checkout', $data)->with('no', 1);
        } else {
            return abort('404');
        }
    }
}

resources/views/cart/cart_items.blade.php
@isset($itemcart)
    @foreach($itemcart->detail as $detail)
<div class="col-12 col-md-12 mb-3">
    <div class="media align-items-center"><div class="panel-heading" style="text-align: center; overflow: hidden; padding: 0;">
        <img class="d-block rounded mr-1" src="{{ asset('image/foto/'.$detail->produk->foto) }}" style="max-height: 60px; min-height:60px; max-width: 60px; min-width:60px; object-fit:cover;" class="image-fluid card-img-top "  alt="..." >
    </div>

        <div class="media-body">
            <i class="ficon cart-item-remove" id="btn-del" data-feather="x" data-id="{{$detail->id}}"></i>
            <div class="media-heading">
                <h6 class="cart-item-title"><a class="text-body" href="app-ecommerce-details.html">
                    {{$detail->produk->nama}}</a>
            </div>
            <div class="btn-group" role="group">
                <input type="hidden" name="param" value="kurang">
                <button class="btn btn-primary btn-sm btn-decrease changeQuantity" data-id="{{$detail->id}}" data-qty="{{$detail->qty}}" 
                    {{$detail->qty<=1?'disabled':''}}>
                -
                </button>
                <button class="btn btn-outline-primary btn-sm" id="qty" disabled="true">
                    {{ number_format($detail->qty) }}
                </button>
                <input type="hidden" name="param" value="tambah">
                <button class="btn btn-primary btn-sm btn-increase changeQuantity" data-id="{{$detail->id}}" data-qty="{{$detail->qty}}">
                +
                </button>
                </div>
                <h5 class="cart-item-price">Rp{{ number_format($detail->subtotal) }}</h5>
        </div>
    </div>
</div>
@endforeach
@endisset

resources/views/cart/checkout.blade.php
@extends('admin.layouts.app')
@section('title','Checkout')
@section('transaksi','active')

@section('content')
<div class="app-content content ecommerce-application">
  <div class="row">
    <div class="col col-8">
      @if (count($errors) > 0)
      @foreach($errors->all() as $error)
          <div class="alert alert-warning">{{ $error }}</div>
      @endforeach
      @endif
      @if ($message = Session::get('error'))
          <div class="alert alert-warning">
              <p>{{ $message }}</p>
          </div>
      @endif
      @if ($message = Session::get('success'))
          <div class="alert alert-success">
              <p>{{ $message }}</p>
          </div>
      @endif
      <div class="row mb-2">
        <div class="col col-12 mb-2">
          <div class="card">
            <div class="card-header">
              Item
            </div>
            <div class="card-body">
              <table class="table table-stripped">
                <thead>
                  <tr>
                    <th>No</th>
                    <th>Produk</th>
                    <th>Harga</th>
                    <th>Diskon</th>
                    <th>Qty</th>
                    <th>Subtotal</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($itemcart->detail as $detail)
                  <tr>
                    <td>
                    {{ $no++ }}
                    </td>
                    <td>
                    {{ $detail->produk->nama }}
                    <br />
                    {{ $detail->produk->kode_produk }}
                    </td>
                    <td>
                    {{ $detail->harga }}
                    </td>
                    <td>
                    {{ $detail->diskon }}
                    </td>
                    <td>
                    {{ $detail->qty }}
                    </td>
                    <td>
                    {{ $detail->subtotal }}
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="col col-12">
          <div class="card">
            <div class="card-header">Alamat Pengiriman</div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-stripped">
                  <thead>
                    <tr>
                      <th>Nama Penerima</th>
                      <th>Alamat</th>
                      <th>No tlp</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                  @if($itemalamatpengiriman)
                    <tr>
                      <td>
                        {{ $itemalamatpengiriman->nama_penerima }}
                      </td>
                      <td>
                        {{ $itemalamatpengiriman->alamat }}<br />
                        {{ $itemalamatpengiriman->kelurahan}}, {{ $itemalamatpengiriman->kecamatan}}<br />
                        {{ $itemalamatpengiriman->city->city_name}}, {{ $itemalamatpengiriman->province->provinces}} - {{ $itemalamatpengiriman->kodepos}}
                      </td>
                      <td>
                        {{ $itemalamatpengiriman->no_tlp }}
                      </td>
                      <td>
                        <a href="{{ route('alamatpengiriman.index') }}" class="btn btn-success btn-sm">
                          Ubah Alamat
                        </a>                        
                      </td>
                    </tr>
                  @endif
                  </tbody>
                </table>
              </div>
            </div>
            <div class="card-footer">
              <a href="{{ route('alamatpengiriman.index') }}" class="btn btn-sm btn-primary">
                Tambah Alamat
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col col-4">
      <div class="card">
        <div class="card-header">
          Ringkasan
        </div>
        <div class="card-body">
          <table class="table">
            <tr>
              <td>No Invoice</td>
              <td class="text-right">
                {{ $itemcart->no_invoice }}
              </td>
            </tr>
            <tr>
              <td>Subtotal</td>
              <td class="text-right">
                Rp{{ $itemcart->subtotal }}
              </td>
            </tr>
            <tr>
              <td>Diskon</td>
              <td class="text-right">
                Rp{{ $itemcart->diskon}}
              </td>
            </tr>
            <tr>
              <td>Ongkir</td>
              <td id="ongkir" class="text-right">
                Rp{{ $itemcart->ongkir}}
              </td>
            </tr>
            <tr>
              <td>Total</td>
              <td id="total" class="text-right">
                Rp{{ $itemcart->total}}
              </td>
            </tr>
          </table>
        </div>
        <div class="card-footer">
          <select data-destination="{{@$itemalamatpengiriman->kota}}" name="courier" id="" class="form-control">
            @isset($itemcart->ekspedisi)
            <option value="{{ old('courier', @$itemcart->ekspedisi) }}">
              {{ strtoupper(old('courier', @$itemcart->ekspedisi))}}{{ $itemcart->where('ekspedisi', 'pos') ? ' Indonesia' : '' }}
            </option>
            @endisset
            <option value="" holder>Pilih Pengiriman</option>
            <option value="jne">JNE</option>
            <option value="tiki">TIKI</option>
            <option value="pos">POS Indonesia</option>
          </select>
          <br>
          <form action="{{ route('transaksi.store') }}" method="post">
            @csrf()
            <button type="submit" class="btn btn-danger btn-block">Buat Pesanan</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection
@push('scripts')
  <script>
    $('select[name="courier"]').on('change', function (){
      var origin = 22;
      var destination = $(this).data('destination');
      var weight = 200;
      var courier = $(this).val();
        $.ajax({
          url: 'getongkir/ajax/' + courier,
          type: "POST",
          data: {
            '_token': $('input[name="_token"]').val(),
            'origin': origin,
            'destination': destination,
            'weight': weight,
            'courier': courier,
          },
          success: function (response) {
          toastr.success(response.message, 'Berhasil!', {
                  closeButton: true,
                  tapToDismiss: false
              });
              $('#ongkir').html('Rp'+(response.ongkir));
              $('#total').html('Rp'+(response.total));
                  
              if (feather) {
                  feather.replace({
                      width: 14,
                      height: 14
                  });
              }
          },
          error: function (data) {
              toastr.error('Kurir gagal dipilih', 'Gagal!', {
                  closeButton: true,
                  tapToDismiss: false
              });
          }
            });
    })
  </script>
@endpush

resources/views/cart/index.blade.php
@extends('admin.layouts.app')
@section('title','Produk')
@section('cart','active')


@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">Produk</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
{{--                                    <li class="breadcrumb-item"><a href="{{route('produk.index')}}">Produk</a>--}}
{{--                                    </li>--}}
                                <li class="breadcrumb-item active">Index
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                <div class="form-group breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
<div class="container">
    <div class="row">
      <div class="col col-md-8">
        @if(count($errors) > 0)
        @foreach($errors->all() as $error)
            <div class="alert alert-warning">{{ $error }}</div>
        @endforeach
        @endif
        @if ($message = Session::get('error'))
            <div class="alert alert-warning">
                <p>{{ $message }}</p>
            </div>
        @endif
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        <div class="card">
          <div class="card-header">
            Item
          </div>
          <div class="card-body">
            <table class="table table-stripped">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Produk</th>
                  <th>Harga</th>
                  <th>Qty</th>
                  <th>Subtotal</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                @isset($itemcart->detail)
                  @foreach($itemcart->detail as $detail)
                    <tr>
                      <td>
                      {{ $no++ }}
                      </td>
                      <td>
                      {{ $detail->produk->nama }}
                      <br />
                      {{ $detail->produk->kode_produk }}
                      </td>
                      <td>
                      {{ ($detail->produk->harga) }}
                      </td>
                      <td>
                        <div class="btn-group" role="group">
                          <form action="{{ route('cartdetail.update',$detail->id) }}" method="post">
                          @method('patch')
                          @csrf()
                            <input type="hidden" name="param" value="kurang">
                            <button class="btn btn-primary btn-sm">
                            -
                            </button>
                          </form>
                          <button class="btn btn-outline-primary btn-sm" disabled="true">
                          {{ $detail->qty }}
                          </button>
                          <form action="{{ route('cartdetail.update',$detail->id) }}" method="post">
                          @method('patch')
                          @csrf()
                            <input type="hidden" name="param" value="tambah">
                            <button class="btn btn-primary btn-sm">
                            +
                            </button>
                          </form>
                        </div>
                      </td>
                      <td>
                      {{ ($detail->subtotal) }}
                      </td>
                      <td>
                      <form action="{{ route('cartdetail.destroy', $detail->id) }}" method="post" style="display:inline;">
                        @csrf
                        {{ method_field('delete') }}
                        <button type="submit" class="btn btn-sm btn-danger mb-2">
                          Hapus
                        </button>                    
                      </form>
                      </td>
                    </tr>
                  @endforeach
                @endisset
                
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col col-md-4">
        <div class="card">
          <div class="card-header">
            Ringkasan
          </div>
          <div class="card-body">
            <table class="table">
              <tr>
                <td>No Invoice</td>
                <td class="text-right">
                  {{ @$itemcart->no_invoice }}
                </td>
              </tr>
              <tr>
                <td>Subtotal</td>
                <td class="text-right">
                  {{ (@$itemcart->subtotal) }}
                </td>
              </tr>
              <tr>
                <td>Diskon</td>
                <td class="text-right">
                  {{ (@$itemcart->diskon) }}
                </td>
              </tr>
              <tr>
                <td>Total</td>
                <td class="text-right">
                  {{ (@$itemcart->total) }}
                </td>
              </tr>
            </table>
          </div>
          <div class="card-footer">
            <div class="row">
              <div class="col">
                <a href="{{ url('checkout') }}" class="btn btn-primary btn-block">
                  Checkout
                </a>
              </div>
              <div class="col">
                <form action="{{ url('kosongkan').'/'.@$itemcart->id }}" method="post">
                  @method('patch')
                  @csrf()
                  <button type="submit" class="btn btn-danger btn-block">Kosongkan</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
  @endsection