routes/web.php
<?php


use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function(){

    //cart
    Route::resource('cart', 'App\Http\Controllers\CartController');
    Route::patch('kosongkan/{id}', 'App\Http\Controllers\CartController@kosongkan');
    // cart detail
    Route::resource('cartdetail', 'App\Http\Controllers\CartDetailController');
    // route transaksi
    Route::resource('transaksi', 'App\Http\Controllers\TransaksiController');
    // alamat pengiriman
    Route::resource('alamatpengiriman', 'App\Http\Controllers\AlamatPengirimanController');
    // checkout
    Route::get('checkout', 'App\Http\Controllers\CartController@checkout');
    // rajaongkir
    Route::get('ongkir', 'App\Http\Controllers\OngkirController@ongkir')->name('ongkir');
    Route::get('getcity/ajax/{id}', 'App\Http\Controllers\OngkirController@getCity')->name('getcity.ajax');
    Route::post('getongkir/ajax/{id}', 'App\Http\Controllers\OngkirController@getOngkir')->name('getongkir.ajax');

    Route::get('/', [App\Http\Controllers\Admin\ProdukController::class, 'index'])->name('/');
    Route::resource('produk', App\Http\Controllers\Admin\ProdukController::class);
    Route::resource('kategori', App\Http\Controllers\Admin\KategoriController::class);
    Route::get('isikategori', [App\Http\Controllers\Admin\KategoriController::class, 'isi']);
    Route::resource('rasa', App\Http\Controllers\Admin\RasaController::class);
    Route::get('isirasa', [App\Http\Controllers\Admin\RasaController::class, 'isi']);
    Route::resource('carabayar', App\Http\Controllers\Admin\BayarController::class);
    Route::resource('pengiriman', App\Http\Controllers\Admin\PengirimanController::class);
    Route::resource('cart-session', App\Http\Controllers\CartSessionController::class);

});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Produk extends Model{
    public $table = 't_produk';
    protected $fillable =[
        'nama',
        'deskripsi',
        'id_kategori',
        'id_rasa',
        'foto',
        'stok',
        'hpp',
        'harga'
    ];
    public function kategori(){
        return $this->belongsTo(Kategori::class, 'id_kategori');
    }
    public function rasa(){
        return $this->belongsTo(Rasa::class, 'id_rasa');
    }
    public function detail() {
        return $this->hasMany(CartDetail::class, 'cart_id');
    }

}

app/Http/Controllers/Admin/ProdukController.php
<?php
namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Produk;
use App\Models\Cart;
use App\Models\CartDetail;
use App\Models\Kategori;
use App\Models\Rasa;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

use Auth;

class ProdukController extends Controller
{
    public function index(Request $request){
        $itemuser = $request->user();//ambil data user
        $itemcart = Cart::where('user_id', $itemuser->id)
                        ->where('status_cart', 'cart')
                        ->first();
        $kategoris = Kategori::all();
        // $cartdetail = CartDetail::where('cart_id', $itemcart->id)->get();
        $data = array('title' => 'Shopping Cart',
                    'itemcart' => $itemcart,
                    // 'cartdetail' => $cartdetail
                    'kategoris' => $kategoris
                    );
        $produks = Produk::orderBy('nama','asc')->get();
        // $data['produk']=DB::table('t_produk')->orderBy('nama')->get();
        // $data['produk'] = Produk::orderBy('nama','asc')->get();

        if(Auth::user()->role == 'admin'){
            return view('admin.produk.index', $data, compact('produks'));
        }
        elseif(Auth::user()->role == 'user'){            
            $cartdetail = CartDetail::where('cart_id', @$itemcart->id)->get();
            $total = $cartdetail->sum('subtotal');
            return view('user.produk.index', $data, compact('cartdetail','produks','total'));
        }
        
    }

    public function kategori($id){
        return response ()->json([
            'message' => 'List Kategori',
            'data' => Produk::where('kategori_id', $id)->get()
        ]);
    }

    public function create(){
        $kategorilist = Kategori::pluck('kategori','id');
        $kategorilist = ['-' => '-Pilih Kategori-'] + collect($kategorilist)->toArray();
        $rasalist = Rasa::pluck('rasa','id');
        $rasalist = ['-' => '-Pilih Rasa-'] + collect($rasalist)->toArray();
        if(Auth::user()->role == 'admin'){
            return view('admin.produk.form', compact('kategorilist','rasalist'));
        }
        elseif(Auth::user()->role == 'user'){
            return redirect('/produk');
        }
    }
    public function store(Request $request){
        $request->validate([
            'nama' => 'required|string',
            'deskripsi' => 'required|string',
            'stok' => 'required|numeric',
            'hpp' => 'required|numeric',
            'harga' => 'required|numeric',
            'foto' => 'required',
            'foto.*' => 'image|mimes:jpeg,png,jpg|max:2048'
        ]);
        $imageName = time() . '.' . $request->foto->extension();
        $request->foto->move(public_path() . '/image/foto/', $imageName);
        $produk = Produk::create([
            'nama' => $request['nama'],
            'deskripsi' => $request['deskripsi'],
            'id_kategori' => $request['id_kategori'],
            'id_rasa' => $request['id_rasa'],
            'stok' => $request['stok'],
            'hpp' => $request['hpp'],
            'harga' => $request['harga'],
            'foto' => $imageName
        ]);
        // unset($input['_token']);
        // $status = DB::table('t_produk')->insert($input);

        if ($produk){
            return redirect('/produk')->with('success','Data berhasil ditambahkan');
        }else{
            return redirect('/produk/create')->with('error','Data gagal ditambahkan');
        }
    }
    public function show($id){
        $produk = Produk::find($id);
        return view('admin.produk.detail', compact('produk'));
    }
    public function edit(Request $request, $id){
        $produk = Produk::find($id);
        $kategorilist = Kategori::pluck('kategori','id');
        $kategorilist = ['0' => '-Pilih Kategori-'] + collect($kategorilist)->toArray();
        $rasalist = Rasa::pluck('rasa','id');
        $rasalist = ['0' => '-Pilih Rasa-'] + collect($rasalist)->toArray();
        if(Auth::user()->role == 'admin'){
            return view('admin.produk.form', compact('kategorilist','rasalist','produk'));
        }
        elseif(Auth::user()->role == 'user'){
            return redirect('/produk');
        }
    }
    public function update( Request $request, $id){
        $request->validate([
            'nama' => 'required|string',
            'deskripsi' => 'required|string',
            'id_kategori' => 'required',
            'stok' => 'required|numeric',
            'hpp' => 'required|numeric',
            'harga' => 'required|numeric',
            'foto.*' => 'image|mimes:jpeg,png,jpg|max:2048'
        ]);
        $produk = Produk::find($id);

        if ($request->foto){
            $imagename = time() . '.' . $request->foto->extension();
            $request->foto->move(public_path() . '/image/foto/', $imagename);
        } else {
            $imagename = $produk->foto;
        }
        $produk->update([
            'nama' => $request['nama'],
            'deskripsi' => $request['deskripsi'],
            'id_kategori' => $request['id_kategori'],
            'id_rasa' => $request['id_rasa'],
            'stok' => $request['stok'],
            'hpp' => $request['hpp'],
            'harga' => $request['harga'],
            'foto' => $imagename
        ]);

        if ($produk){
            return redirect('/produk')->with('success','Data berhasil diubah');
        }else{
            return redirect('/produk/create')->with('error','Data gagal diubah');
        }
    }
    public function destroy($id){
        // $status = DB::table('t_produk')->where('id',$id)->delete();
        $produk = Produk::find($id);
        $status = $produk->delete();
        if ($status){
            return redirect('/produk')->with('success','Data berhasil dihapus');
        }else{
            return redirect('/produk/create')->with('error','Data gagal dihapus');
        }
    }
}

resources/views/admin/produk/form.blade.php
@extends('admin.layouts.app')
@section('title')
     Form {{@$produk ? ' Ubah' : ' Tambah'}}
@endsection
@section('produk','active')
@section('content')

    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Data Produk</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{url('produk')}}">Index</a>
                                    </li>
                                @isset($produk->id)
                                    <li class="breadcrumb-item"> <a href="{{route('produk.show',$produk->id)}}">Detail Produk</a>
                                    </li>
                                @endisset
                                    
                                    <li class="breadcrumb-item active">{{(@$produk ? ' Ubah' : ' Tambah')}} Produk
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Tables start -->@can('isAdmin')
                <section id="basic-vertical-layouts">
                    <div class="row">
                        <div class=" col-12">
                            <div class="card">
                                <div class="card-body">
                                    @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <h4 class="alert-heading">Error!</h4>
                                            <div class="alert-body">
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        </div>
                                    @endif
                                    
                                    <form class="form form-vertical"  action="{{@$produk ? route('produk.update',$produk->id) : route('produk.store')}}"
                                          method="POST" enctype="multipart/form-data">
                                        @csrf
                                        @if(@$produk)
                                            {{method_field('patch')}}
                                        @endif
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <form enctype="multipart/form-data" action="{{@$produk ? url('produk',@$produk->id) : url('produk')}}" method="POST">
                                                        @csrf
                                                    
                                                        @if(!empty(@$produk))
                                                            @method('PATCH')
                                                        @endif
                                                    
                                                        <h5>Nama Produk :</h5> <input type="text" class="form-control" name="nama" value="{{ old('nama', @$produk->nama) }}"><br>
                                                        <h5>Deskripsi Produk :</h5> <textarea type="text" class="form-control" name="deskripsi" value="{{old('deskripsi', @$produk->deskripsi)}}">{{old('deskripsi', @$produk->deskripsi)}}</textarea> <br>
                                                        {{Form::label('id_kategori', 'Kategori',['class'=>'h5'])}}
                                                        {{Form::select('id_kategori', $kategorilist, null, ['class' =>'form-control'])}} 
                                                        <br>
                                                        {{Form::label('id_rasa', 'Rasa',['class'=>'h5'])}}
                                                        {{Form::select('id_rasa', $rasalist, null, ['class' =>'form-control'])}} 
                                                        <br>
                                                        <h5>Stok :</h5> <input type="number" min="0" class="form-control" name="stok" value="{{ old('stok', @$produk->stok) }}"><br>
                                                        <h5>Hpp  :</h5> <input type="number" min="0" class="form-control" name="hpp" value="{{ old('hpp', @$produk->hpp) }}"><br>
                                                        <h5>Harga  :</h5> <input type="number" min="0" class="form-control" name="harga" value="{{ old('harga', @$produk->harga) }}"><br>
                                                        <h5>Foto  :</h5> <input type="file" class="form-control" name="foto" value="{{ old('foto', @$produk->foto) }}"><br>
                                                </div>
                                            </div>

                                            <div class="col-12">
                                                <button type="submit" class="btn btn-primary mr-1">Submit</button>
                                                @isset($produk->id)
                                                <a href="{{route('produk.show', $produk->id)}}" type="reset" class="btn btn-outline-secondary">Cancel</a>
                                                @endisset
                                                @empty($produk->id)
                                                <a href="{{url('produk')}}" type="reset" class="btn btn-outline-secondary">Cancel</a>
                                                @endempty
                                            </div>
                                            </form>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                @elsecan('isUser')
                <meta http-equiv="refresh" content="0; url=http://127.0.0.1:8181/produk">
                @endcan
                <!-- Basic Tables end -->
            </div>
        </div>
    </div>
    @endsection

@push('styles')
@endpush

@push('scripts')
    <script>

    </script>
@endpush